### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Zren** [comment]
I manually merged to avoid conflicts with another translation PR. You don't need to edit the ReadMe % as the release scripts will do it for you.

**Comment by Vistaus** [comment]
Sorry 'bout that! Just for clarification: do I need to run the release script next time after updating the translation or is that something you do?

**Comment by Zren** [comment]
I'll run the `./merge` script when building a release to update the `ReadMe.md` percentages.

**Comment by Vistaus** [comment]
Ah, I see. I will stay away from the readme and release script next time then. 🙂

**Pull request closed without merging**
