### PR TITLE
Add Hebrew translation

### PR DESCRIPTION
**Pull request by omeritzics**
[hebrew.txt](https://github.com/Zren/plasma-applet-tiledmenu/files/5381266/hebrew.txt)

### CODE REVIEW

**Comment by Zren** [comment]
Looks good. No idea if this following comment above the "px" message will stay when I `msgmerge` that's fine.
```
# הרווח בהתחלה הוא מכוון.
# אם ברצונך למחוק את הרווח, יש למחוק גם את התרגום למחרוזת זו.
```

Subscribe to the Translation Updates issue if you'd like to be notified via email about new messages to translate.

**Comment by Zren** [comment]
Hmmm, it translated okay, but my code doesn't support right to left text very well it seems.

**Comment by Zren** [comment]
Looks like I needed to add the following to `ConfigPage.qml` to flip the layout. It's not perfect, but it's definitely better than before.

```qml
LayoutMirroring.enabled: Qt.application.layoutDirection == Qt.RightToLeft
LayoutMirroring.childrenInherit: true
```

**Comment by omeritzics** [comment]
> Looks good. No idea if this following comment above the "px" message will stay when I `msgmerge` but that's fine.
> 
> ```
> # הרווח בהתחלה הוא מכוון.
> # אם ברצונך למחוק את הרווח, יש למחוק גם את התרגום למחרוזת זו.
> ```
> 
> Subscribe to the Translation Updates issue if you'd like to be notified via email about new messages to translate.

This note is for other Hebrew translators.

**Pull request merged**
